[build]
  publish = "."
  command = "echo 'Static HTML site - no build needed'"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
