-- reviews 테이블 생성
CREATE TABLE IF NOT EXISTS reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text,
    email text,
    phone text,
    source text,
    education text,
    company text,
    postcode text,
    road_address text,
    detail_address text,
    work_type text,
    major_job_code text,
    sub_job_code text,
    start_date date,
    end_date date,
    proof_url text,
    reviews_data jsonb
);

-- Supabase Storage에 'proofs' 버킷 생성 안내
-- 이 스크립트는 버킷을 직접 생성하지 않습니다.
-- Supabase 대시보드의 Storage 섹션에서 'proofs'라는 이름의 공개(public) 버킷을 생성해주세요.
-- 공개 버킷 정책 예시:
-- {
--   "name": "public_proofs",
--   "id": "public_proofs",
--   "owner": "",
--   "public": true,
--   "file_size_limit": null,
--   "allowed_mime_types": null
-- }
