-- reviews 테이블 생성
CREATE TABLE IF NOT EXISTS reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text,
    email text,
    phone text,
    source text,
    education text,
    company text,
    postcode text,
    road_address text,
    detail_address text,
    work_type text,
    major_job_code text,
    sub_job_code text,
    start_date date,
    end_date date,
    proof_url text,
    reviews_data jsonb
);
